CREATE TABLE products
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url LONGVARCHAR,
    name LONGVARCHAR NOT NULL,
    price DECIMAL(19,2) NOT NULL
);
CREATE TABLE fields
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prducts_count INT NOT NULL,
    internal_id LONGVARCHAR NOT NULL,
    position INT,
    product_id INT,
    CONSTRAINT FK_p22th1vlbrm7wcpr2b9pm4wfn FOREIGN KEY (product_id) REFERENCES products (id)
);
CREATE INDEX FK_p22th1vlbrm7wcpr2b9pm4wfn ON fields (product_id);
CREATE TABLE rows
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id LONGVARCHAR
);
CREATE TABLE machines
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name LONGVARCHAR
);
CREATE TABLE machine_rows
(
    machine INT NOT NULL,
    row INT NOT NULL,
    CONSTRAINT FK_5voaw43luxqyqoofooogt7nlw FOREIGN KEY (row) REFERENCES rows (id),
    CONSTRAINT FK_ea7948qsiyjwcj5grhxpesiq2 FOREIGN KEY (machine) REFERENCES machines (id)
);
CREATE INDEX FK_ea7948qsiyjwcj5grhxpesiq2 ON machine_rows (machine);
CREATE UNIQUE INDEX UK_5voaw43luxqyqoofooogt7nlw ON machine_rows (row);
CREATE TABLE row_fields
(
    row INT NOT NULL,
    field INT NOT NULL,
    CONSTRAINT FK_m07odu6ul2it8huaw8omfs5cg FOREIGN KEY (row) REFERENCES rows (id),
    CONSTRAINT FK_sovjpubfae0t9yfuotuengu81 FOREIGN KEY (field) REFERENCES fields (id)
);
CREATE INDEX FK_m07odu6ul2it8huaw8omfs5cg ON row_fields (row);
CREATE UNIQUE INDEX UK_sovjpubfae0t9yfuotuengu81 ON row_fields (field);
