CREATE TABLE categories
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE products
(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    image_url VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    price DECIMAL(19,2) NOT NULL,
    addedTime TINYBLOB,
    description VARCHAR(255),
    imageData MEDIUMBLOB,
    id_categories BIGINT(20),
    CONSTRAINT FK_8l3my8ls6adnevblpj5twva2e FOREIGN KEY (id_categories) REFERENCES categories (id)
);
CREATE INDEX FK_8l3my8ls6adnevblpj5twva2e ON products (id_categories);

CREATE TABLE fields
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prducts_count INT NOT NULL,
    internal_id LONGVARCHAR NOT NULL,
    position INT,
    product_id INT,
    CONSTRAINT FK_p22th1vlbrm7wcpr2b9pm4wfn FOREIGN KEY (product_id) REFERENCES products (id)
);
CREATE INDEX FK_p22th1vlbrm7wcpr2b9pm4wfn ON fields (product_id);
CREATE TABLE rows
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id LONGVARCHAR
);
CREATE TABLE machines
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name LONGVARCHAR
);
CREATE TABLE machine_rows
(
    machine INT NOT NULL,
    row INT NOT NULL,
    CONSTRAINT FK_5voaw43luxqyqoofooogt7nlw FOREIGN KEY (row) REFERENCES rows (id),
    CONSTRAINT FK_ea7948qsiyjwcj5grhxpesiq2 FOREIGN KEY (machine) REFERENCES machines (id)
);
CREATE INDEX FK_ea7948qsiyjwcj5grhxpesiq2 ON machine_rows (machine);
CREATE UNIQUE INDEX UK_5voaw43luxqyqoofooogt7nlw ON machine_rows (row);
CREATE TABLE row_fields
(
    row INT NOT NULL,
    field INT NOT NULL,
    CONSTRAINT FK_m07odu6ul2it8huaw8omfs5cg FOREIGN KEY (row) REFERENCES rows (id),
    CONSTRAINT FK_sovjpubfae0t9yfuotuengu81 FOREIGN KEY (field) REFERENCES fields (id)
);
CREATE INDEX FK_m07odu6ul2it8huaw8omfs5cg ON row_fields (row);
CREATE UNIQUE INDEX UK_sovjpubfae0t9yfuotuengu81 ON row_fields (field);
