ALTER TABLE purchases MODIFY COLUMN time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE products MODIFY COLUMN addedTime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE purchases DROP COLUMN id;
ALTER TABLE purchases ADD COLUMN id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE fields CHANGE product_id product INT(11);